name: Frist Workfllow

on: 
  push:
    branches:
     - main 

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "wellcome to our frist GitHub Actions WorkFlow!"
        
      - name: Checkout repository
        uses: actions/checkout@5.0.0

      - name: List repositeory files
        run: ls -la
